### ISSUE TITLE
TypeError: Object of type KeycloakRole is not JSON serializable

### ISSUE THREAD

**Issue by fherrera124** [code-specialist/fastapi-keycloak#30] opened 2022-03-27 08:02 UTC
Whenever I try to create an user with an initial role, I get the error: "TypeError: Object of type KeycloakRole is not JSON serializable"

**Comment by yannicschroeer** [comment] 2022-03-27 09:18
Hi @fherrera124, unfortunately I wasn't able to reproduce the error. Could you please provide the whole user you're trying to register and at which point you get the serializing error?

**Comment by fherrera124** [comment] 2022-03-27 09:40
Sure, this is my function:

```
@app.post("/users", tags=["user-management"])
def create_user(first_name: str, last_name: str, email: str, password: SecretStr, initial_roles: List[str]):
    return idp.create_user(first_name=first_name, last_name=last_name,
                           username=email, email=email, password=password.get_secret_value(),
                           initial_roles=initial_roles, send_email_verification=False)
```

This is the list containing a valid role:

```
[
  "SUBCOORDINADOR_REGIONAL"
]
```

The output of the error:

```
File "/home/server/dockers/xxxx/app/app.py", line 57, in create_user
    return idp.create_user(first_name=first_name, last_name=last_name,
  File "/home/server/.cache/pypoetry/virtualenvs/xxxx-7DESS4RH-py3.8/lib/python3.8/site-packages/fastapi_keycloak/api.py", line 57, in wrapper
    result: Response = f(*args, **kwargs)  # The actual call
  File "/home/server/.cache/pypoetry/virtualenvs/xxxx-7DESS4RH-py3.8/lib/python3.8/site-packages/fastapi_keycloak/api.py", line 686, in create_user
    response = self._admin_request(url=self.users_uri, data=data, method=HTTPMethod.POST)
  File "/home/server/.cache/pypoetry/virtualenvs/xxxx-7DESS4RH-py3.8/lib/python3.8/site-packages/fastapi_keycloak/api.py", line 913, in _admin_request
    return requests.request(method=method.name, url=url, data=json.dumps(data), headers=headers)
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeycloakRole is not JSON serializable
```

**Comment by yannicschroeer** [comment] 2022-03-27 10:48
Seems like the response by Keycloak isn't valid JSON or mismatches the Pydantic model. Could you please debug into the Keycloak response (E.g. breakpoint at line 59 of `fastapi_keycloak/api.py`) and provide a (safe) version of the response provided by Keycloak?

**Comment by fherrera124** [comment] 2022-03-27 14:50
The object returned:

`[KeycloakRole(id='xxxxxx2', name='SUBCOORDINADOR_REGIONAL', composite=False, clientRole=False, containerId='Test')]`

**Comment by yannicschroeer** [comment] 2022-03-27 15:16
This was indeed an issue. The initial roles were directly dumped to JSON from the Pydantic model which didn't work quite well. Should be fixed in `1.0.2` I just released

**Comment by fherrera124** [comment] 2022-03-27 15:24
Thanks, great work.

**Comment by fherrera124** [comment] 2022-03-27 15:51
> This was indeed an issue. The initial roles were directly dumped to JSON from the Pydantic model which didn't work quite well. Should be fixed in `1.0.2` I just released

Just tested, it always returns error 500 :/

So, for now, first I'm creating the user, and then adding the role to that user (yesterday it worked).

PD: New bug introduced, if there are no initial roles, now fails with this:

```
File "/usr/local/lib/python3.8/site-packages/fastapi_keycloak/api.py", line 664, in create_user
    initial_roles_json = [role.dict() for role in initial_roles]
TypeError: 'NoneType' object is not iterable
```

**Comment by yannicschroeer** [comment] 2022-03-27 17:55
Turns out I tested the wrong version 🥲 Also, the Keycloak documentation was misleading so the `clientRoles` field was totally wrong, the `realmRoles` field is the correct one. Should be fixed once and for all in v1.0.3.

**Comment by fherrera124** [comment] 2022-03-27 18:40
Thanks, the errors are gone now. But from the KeyCloak Admin Console I'm seeing that the new users don't get the initial roles. It's no big deal for me, I will stick with the procedure of creating users without roles, and then add them.

**Comment by fherrera124** [comment] 2022-03-27 18:47
[Seems like a old know bug](https://stackoverflow.com/a/57416390/5739532)

**Comment by yannicschroeer** [comment] 2022-03-27 19:07
Hmm, seems like that's the case... thanks for pointing that out. For convenience, I'll change the API to make additional requests for the initial roles for now

**Comment by yannicschroeer** [comment] 2022-03-27 19:29
I'll not say "it's fixed" anymore. But I think it's finally working as expected. Though I had to add the initial roles in additional requests.

**Comment by yannicschroeer** [comment] 2022-03-27 19:39
May also be related to https://github.com/keycloak/keycloak/issues/9342. Further introspection required.

**Closed** 2022-04-13 07:24 UTC
Labels: bug
